/**
 * `ship generate` — reads the project's `ship.config.ts` and emits typed SDK
 * wiring plus per-model admin pages into `apps/web/src/`. The pure render
 * helpers below are unit-testable without a real project: they take a list of
 * `ModelDefinition`s and return file contents, while the `generateAdminPages`
 * factory only adds the filesystem writes.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { lowerFirst, type ModelDefinition } from '@ship/core';
import { info, success } from '../term';

/* ─────────────────────────── Label helpers ─────────────────────────── */

/**
 * Convert a camelCase field name into a human-readable label:
 * `publishedAt` → `Published At`, `title` → `Title`.
 */
export function humanize(field: string): string {
  return field
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(' ')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/** Plural-friendly nav label: `Post` → `Posts`, `Media` → `Media`. */
function navLabel(model: ModelDefinition): string {
  const admin = model.options.admin;
  return admin?.pluralLabel ?? admin?.label ?? humanize(model.collection);
}

/** Field kinds rendered as list columns by default (compact, scannable). */
const LIST_SCALAR_KINDS: Record<string, true> = {
  text: true,
  url: true,
  email: true,
  slug: true,
  integer: true,
  decimal: true,
  float: true,
  boolean: true,
  select: true,
  multiSelect: true,
  datetime: true,
  date: true,
  time: true,
  relation: true,
};

function defaultListFields(model: ModelDefinition): string[] {
  return Object.keys(model.fields).filter(
    (field) => LIST_SCALAR_KINDS[model.fields[field].kind] === true,
  );
}

/** Best label field for a relation picker: searchField, else first text-ish. */
function relationLabelField(model: ModelDefinition): string {
  const admin = model.options.admin;
  if (admin?.searchField) return admin.searchField;
  for (const [field, def] of Object.entries(model.fields)) {
    if (def.kind === 'email' || def.kind === 'text' || def.kind === 'slug') {
      return field;
    }
  }
  return 'id';
}

/** Initial form values from field `default`s. */
function defaultValues(model: ModelDefinition): string {
  const entries = Object.entries(model.fields)
    .map(([field, def]) => {
      const value = (def.options as Record<string, unknown>).default;
      return { field, value };
    })
    .filter((entry) => entry.value !== undefined)
    .map((entry) => `    ${entry.field}: ${JSON.stringify(entry.value)},`);
  if (entries.length === 0) return '{}';
  return `{\n${entries.join('\n')}\n  }`;
}

/* ─────────────────────────── Path planning ─────────────────────────── */

/** Relative (to `outDir`) paths that `generateAdminPages` will write. */
export function planGeneratePages(models: ModelDefinition[]): string[] {
  const paths = ['lib/admin-nav.ts', 'lib/ship.ts', 'app/admin/page.tsx'];
  for (const model of models) {
    const base = `app/admin/${model.collection}`;
    paths.push(
      `${base}/page.tsx`,
      `${base}/new/page.tsx`,
      `${base}/[id]/page.tsx`,
    );
  }
  return paths;
}

/* ─────────────────────────── Renderers ───────────────────────────── */

/** `lib/admin-nav.ts` — typed nav: Dashboard plus one entry per visible model. */
function renderNav(models: ModelDefinition[]): string {
  const items = models
    .filter((m) => !m.options.admin?.hidden)
    .map((m) => {
      const admin = m.options.admin ?? {};
      const fields = [`label: '${navLabel(m)}'`, `href: '/admin/${m.collection}'`];
      if (admin.icon) fields.push(`icon: '${admin.icon}'`);
      if (admin.description) fields.push(`description: '${admin.description}'`);
      if (admin.group) fields.push(`group: '${admin.group}'`);
      return `  { ${fields.join(', ')} },`;
    })
    .join('\n');
  return `// Generated by \`ship generate\` — edit freely; regenerated on next generate.
export interface AdminNavItem {
  label: string;
  href: string;
  icon?: string;
  description?: string;
  group?: string;
}

export const adminNav: AdminNavItem[] = [
  { label: 'Dashboard', href: '/admin' },
${items}
];
`;
}

/** `lib/ship.ts` — model re-exports, one `createModelApi` + relation lookup per model. */
function renderShip(models: ModelDefinition[]): string {
  const names = models.map((m) => m.name).join(', ');
  const entries = models
    .map((m) => `  ${lowerFirst(m.name)}: createModelApi(${m.name}, { baseUrl: url }),`)
    .join('\n');
  const relationEntries = models
    .map((m) => {
      const camel = lowerFirst(m.name);
      const labelField = relationLabelField(m);
      return `  ${m.name}: (q?: string) => ship.${camel}.findMany({ q, take: 20 }).then((rows) => rows.map((r) => ({ id: r.id, label: String(r.${labelField} ?? r.id) }))),`;
    })
    .join('\n');
  return `// Generated by \`ship generate\` — edit freely; regenerated on next generate.
import { ${names} } from '../../../../ship.config';
import { createModelApi } from '@ship/sdk';

export { ${names} };

const url = \`\${process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001'}\`;

export const ship = {
${entries}
};

export const relations = {
${relationEntries}
};
`;
}

/** Table column definitions for a list page, ending in an Actions column. */
function renderColumns(model: ModelDefinition): string {
  const admin = model.options.admin ?? {};
  const fields = admin.listFields ?? defaultListFields(model);
  const columns = fields
    .filter((field) => field in model.fields)
    .map(
      (field) =>
        `    { field: '${field}', label: '${humanize(field)}', sortable: true, render: (row: any) => formatValue('${field}', row) },`,
    );
  columns.push(`    {
      label: 'Actions',
      render: (row: any) => (
        <div className="flex gap-1">
          <Link href={\`/admin/${model.collection}/\${row.id}\`}>
            <ShipButton variant="ghost" size="sm">Edit</ShipButton>
          </Link>
          <ShipButton variant="ghost" size="sm" className="text-error" onClick={() => removeRow(row)}>
            Delete
          </ShipButton>
        </div>
      ),
    },`);
  return columns.join('\n');
}

/** Per-field `<ShipField>` blocks shared by the create and edit pages. */
function renderFields(model: ModelDefinition): string {
  return Object.keys(model.fields)
    .map((field) =>
      [
        `          <ShipField`,
        `            key="${field}"`,
        `            name="${field}"`,
        `            label="${humanize(field)}"`,
        `            def={${model.name}.fields['${field}']}`,
        `            value={values['${field}']}`,
        `            onChange={(v) => setValues((p) => ({ ...p, ${field}: v }))}`,
        `            relations={relations}`,
        `            uploadUrl={uploadUrl}`,
        `          />`,
      ].join('\n'),
    )
    .join('\n');
}

/** `app/admin/<collection>/page.tsx` — searchable, sortable, paginated list. */
function renderList(model: ModelDefinition): string {
  const { name, collection } = model;
  const camel = lowerFirst(name);
  const admin = model.options.admin ?? {};
  const sort = admin.defaultSort ?? { field: 'createdAt', order: 'desc' };
  const sortField = sort.field ?? 'createdAt';
  const sortOrder = sort.order ?? 'desc';
  const descLine = admin.description
    ? `          <p className="text-sm text-base-content/60">${admin.description}</p>`
    : '';
  return `'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ShipTable, ShipButton, ShipSearchInput, ShipPagination, ShipEmptyState, ShipBadge, ShipConfirmDialog, useToast, type Column } from '@ship/ui';
import { ship, ${name} } from '@/lib/ship';

const api = ship.${camel};
const PAGE_SIZE = 20;

function formatValue(field: keyof typeof ${name}.fields, row: any) {
  const value = row[field];
  if (value == null || value === '') return <span className="text-base-content/40">—</span>;
  const def = ${name}.fields[field];
  switch (def.kind) {
    case 'boolean':
      return value ? <ShipBadge tone="success">True</ShipBadge> : <ShipBadge tone="neutral">False</ShipBadge>;
    case 'select':
      return <ShipBadge>{String(value)}</ShipBadge>;
    case 'datetime':
      return new Date(value).toLocaleString();
    case 'date':
      return new Date(value).toLocaleDateString();
    case 'relation':
      return <span className="text-base-content/70">{String(value)}</span>;
    default: {
      const s = String(value);
      return s.length > 60 ? s.slice(0, 60) + '…' : s;
    }
  }
}

/**
 * ${name} list — generated by \`ship generate\`.
 */
export default function ${name}ListPage() {
  const router = useRouter();
  const toast = useToast();
  const [rows, setRows] = useState<any[]>([]);
  const [q, setQ] = useState('');
  const [page, setPage] = useState(1);
  const [hasNext, setHasNext] = useState(false);
  const [sortField, setSortField] = useState('${sortField}');
  const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>('${sortOrder}');
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [hidden, setHidden] = useState<Set<string>>(new Set());
  const [confirm, setConfirm] = useState<{ message: string; action: () => Promise<void> } | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const orderBy = sortOrder === 'desc' ? \`-\${sortField}\` : sortField;
      const next = await api.findMany({ q: q || undefined, take: PAGE_SIZE + 1, skip: (page - 1) * PAGE_SIZE, orderBy });
      setHasNext(next.length > PAGE_SIZE);
      setRows(next.slice(0, PAGE_SIZE));
    } catch {
      setRows([]);
      setHasNext(false);
    } finally {
      setLoading(false);
    }
  }, [q, page, sortField, sortOrder]);

  useEffect(() => {
    const t = setTimeout(load, q ? 250 : 0);
    return () => clearTimeout(t);
  }, [load, q]);

  useEffect(() => {
    setPage(1);
  }, [q]);

  function askConfirm(message: string, action: () => Promise<void>) {
    setConfirm({ message, action });
  }

  function toggleSelect(id: string) {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function toggleSelectAll() {
    setSelected((prev) => {
      const allSelected = rows.every((r) => prev.has(r.id));
      const next = new Set(prev);
      for (const r of rows) {
        if (allSelected) next.delete(r.id);
        else next.add(r.id);
      }
      return next;
    });
  }

  function toggleColumn(field: string) {
    setHidden((prev) => {
      const next = new Set(prev);
      if (next.has(field)) next.delete(field);
      else next.add(field);
      return next;
    });
  }

  async function removeRow(row: any) {
    askConfirm(\`You are about to delete 1 ${name}. This cannot be undone.\`, async () => {
      try {
        await api.delete(row.id);
        toast('${name} deleted');
        load();
      } catch {
        toast('Failed to delete ${name}', 'error');
      }
    });
  }

  async function bulkDelete() {
    const ids = [...selected];
    askConfirm(\`You are about to delete \${selected.size} ${name} \${selected.size === 1 ? 'record' : 'records'}. This cannot be undone.\`, async () => {
      try {
        await Promise.all(ids.map((id) => api.delete(id)));
        toast(\`\${ids.length} ${name} deleted\`);
        setSelected(new Set());
        load();
      } catch {
        toast('Failed to delete some records', 'error');
      }
    });
  }

  const columns: Column<any>[] = [
${renderColumns(model)}
  ];

  const visibleColumns = columns.filter((c) => c.field == null || !hidden.has(c.field));

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold">${name}</h1>
${descLine}
        </div>
        <ShipButton onClick={() => router.push('/admin/${collection}/new')}>New ${name}</ShipButton>
      </div>

      <div className="flex items-center justify-between gap-3">
        <ShipSearchInput value={q} onChange={setQ} placeholder="Search…" />
        <details className="dropdown">
          <summary className="btn btn-sm btn-ghost">Columns</summary>
          <ul className="menu dropdown-content z-20 w-56 rounded-box border border-base-300 bg-base-100 p-2 shadow-lg">
            {columns.map((c) => {
              const field = c.field;
              return field ? (
                <li key={c.label}>
                  <label className="flex cursor-pointer items-center gap-2">
                    <input type="checkbox" className="checkbox checkbox-sm" checked={!hidden.has(field)} onChange={() => toggleColumn(field)} />
                    {c.label}
                  </label>
                </li>
              ) : null;
            })}
          </ul>
        </details>
      </div>

      {selected.size > 0 ? (
        <div className="flex items-center justify-between rounded bg-primary/10 px-3 py-2 text-sm">
          <span className="font-medium">{selected.size} selected</span>
          <ShipButton size="sm" variant="danger" onClick={bulkDelete}>Delete</ShipButton>
        </div>
      ) : null}

      {loading ? (
        <div className="flex justify-center py-16"><span className="loading loading-spinner loading-lg" /></div>
      ) : rows.length === 0 ? (
        <ShipEmptyState
          title={q ? 'No matches' : 'No records yet'}
          description={q ? 'Try a different search.' : 'This collection is empty — create your first record.'}
          action={<ShipButton onClick={() => router.push('/admin/${collection}/new')}>New ${name}</ShipButton>}
        />
      ) : (
        <ShipTable
          data={rows}
          columns={visibleColumns}
          rowKey={(r) => r.id}
          sortField={sortField}
          sortOrder={sortOrder}
          onSort={(field, order) => { setSortField(field); setSortOrder(order); setPage(1); }}
          selectable
          selectedKeys={selected}
          onSelectRow={toggleSelect}
          onSelectAll={toggleSelectAll}
        />
      )}

      {rows.length > 0 ? <ShipPagination page={page} hasNext={hasNext} onPage={setPage} /> : null}

      <ShipConfirmDialog
        open={confirm != null}
        title="Confirm deletion"
        message={confirm?.message ?? ''}
        onCancel={() => setConfirm(null)}
        onConfirm={() => { const action = confirm?.action; setConfirm(null); if (action) action(); }}
      />
    </div>
  );
}
`;
}

/** `app/admin/<collection>/new/page.tsx` — create page. */
function renderCreate(model: ModelDefinition): string {
  const { name, collection } = model;
  const camel = lowerFirst(name);
  return `'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ShipField, ShipButton, ShipCard, useToast } from '@ship/ui';
import { ship, ${name}, relations } from '@/lib/ship';

const api = ship.${camel};
const uploadUrl = \`\${process.env.NEXT_PUBLIC_API_URL}/upload\`;

/**
 * New ${name} — generated by \`ship generate\`.
 */
export default function New${name}Page() {
  const router = useRouter();
  const toast = useToast();
  const [values, setValues] = useState<Record<string, unknown>>(${defaultValues(model)});
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  async function submit(e: { preventDefault(): void }) {
    e.preventDefault();
    setSaving(true);
    setError('');
    try {
      await api.create(values as any);
      toast('${name} created');
      router.push('/admin/${collection}');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create ${name}');
      setSaving(false);
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">New ${name}</h1>
        <Link href="/admin/${collection}">
          <ShipButton variant="ghost">Cancel</ShipButton>
        </Link>
      </div>

      <form onSubmit={submit} className="space-y-6">
        <ShipCard>
          <div className="space-y-5">
${renderFields(model)}
          </div>
        </ShipCard>
        {error ? <div className="alert alert-error"><span>{error}</span></div> : null}
        <div className="flex justify-end">
          <ShipButton type="submit" disabled={saving} loading={saving}>Save</ShipButton>
        </div>
      </form>
    </div>
  );
}
`;
}

/** `app/admin/<collection>/[id]/page.tsx` — edit page. */
function renderEdit(model: ModelDefinition): string {
  const { name, collection } = model;
  const camel = lowerFirst(name);
  return `'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { ShipField, ShipButton, ShipCard, useToast } from '@ship/ui';
import { ship, ${name}, relations } from '@/lib/ship';

const api = ship.${camel};
const uploadUrl = \`\${process.env.NEXT_PUBLIC_API_URL}/upload\`;

/**
 * Edit ${name} — generated by \`ship generate\`.
 */
export default function Edit${name}Page() {
  const router = useRouter();
  const params = useParams();
  const toast = useToast();
  const id = params.id as string;
  const [values, setValues] = useState<Record<string, unknown>>({});
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    let active = true;
    api.findById(id)
      .then((row) => {
        if (active && row) setValues(row as any);
      })
      .catch(() => {})
      .finally(() => {
        if (active) setLoading(false);
      });
    return () => {
      active = false;
    };
  }, [id]);

  async function submit(e: { preventDefault(): void }) {
    e.preventDefault();
    setSaving(true);
    setError('');
    try {
      await api.update(id, values as any);
      toast('${name} updated');
      router.push('/admin/${collection}');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to update ${name}');
      setSaving(false);
    }
  }

  if (loading) {
    return (
      <div className="flex justify-center py-24">
        <span className="loading loading-spinner loading-lg" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Edit ${name}</h1>
        <Link href="/admin/${collection}">
          <ShipButton variant="ghost">Cancel</ShipButton>
        </Link>
      </div>

      <form onSubmit={submit} className="space-y-6">
        <ShipCard>
          <div className="space-y-5">
${renderFields(model)}
          </div>
        </ShipCard>
        {error ? <div className="alert alert-error"><span>{error}</span></div> : null}
        <div className="flex justify-end">
          <ShipButton type="submit" disabled={saving} loading={saving}>Save</ShipButton>
        </div>
      </form>
    </div>
  );
}
`;
}

/** `app/admin/page.tsx` — dashboard, one card per collection from `adminNav`. */
function renderDashboard(): string {
  return `'use client';

import Link from 'next/link';
import { adminNav } from '@/lib/admin-nav';

/**
 * Admin dashboard — one card per collection, driven by \`adminNav\`.
 */
export default function AdminDashboardPage() {
  const models = adminNav.filter((item) => item.href !== '/admin');
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold">Dashboard</h1>
        <p className="text-sm text-base-content/60">
          Manage your content, media, and settings from one place.
        </p>
      </div>
      {models.length === 0 ? (
        <p className="text-base-content/60">No collections defined yet.</p>
      ) : (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {models.map((m) => (
            <Link
              key={m.href}
              href={m.href}
              className="card border border-base-300 bg-base-100 shadow-sm transition hover:border-primary hover:shadow-md"
            >
              <div className="card-body">
                <div className="flex items-center gap-3">
                  <span className="grid h-10 w-10 place-items-center rounded-lg bg-primary/10 text-lg font-semibold text-primary">
                    {m.icon ?? m.label.charAt(0)}
                  </span>
                  <h2 className="card-title">{m.label}</h2>
                </div>
                {m.description ? (
                  <p className="text-sm text-base-content/60">{m.description}</p>
                ) : null}
              </div>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
`;
}

/* ─────────────────────────── Writers ─────────────────────────── */

async function emit(outDir: string, rel: string, content: string): Promise<void> {
  const target = join(outDir, rel);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, content, 'utf8');
}

/**
 * Write the full admin tree (nav, SDK entry, dashboard, and list/create/edit
 * pages) for every model under `options.outDir`.
 */
export async function generateAdminPages(
  models: ModelDefinition[],
  options: { outDir: string },
): Promise<void> {
  const { outDir } = options;
  await emit(outDir, 'lib/admin-nav.ts', renderNav(models));
  await emit(outDir, 'lib/ship.ts', renderShip(models));
  await emit(outDir, 'app/admin/page.tsx', renderDashboard());
  for (const model of models) {
    const base = `app/admin/${model.collection}`;
    await emit(outDir, `${base}/page.tsx`, renderList(model));
    await emit(outDir, `${base}/new/page.tsx`, renderCreate(model));
    await emit(outDir, `${base}/[id]/page.tsx`, renderEdit(model));
  }
}

/* ─────────────────────────── CLI entry ─────────────────────────── */

/** Dynamically load `<cwd>/ship.config.ts` and return its `models`. */
export async function loadModels(cwd: string): Promise<ModelDefinition[]> {
  const configUrl = pathToFileURL(join(cwd, 'ship.config.ts')).href;
  // Dynamic import: the project config path is only known at runtime (`cwd`).
  const mod = (await import(configUrl)) as {
    default?: { models?: ModelDefinition[] };
  };
  return mod.default?.models ?? [];
}

/**
 * Run `ship generate` inside a generated project: load its config and emit the
 * admin tree under `apps/web/src`, logging each written file's relative path.
 */
export async function runGenerate(cwd: string = process.cwd()): Promise<void> {
  const models = await loadModels(cwd);
  await generateAdminPages(models, { outDir: join(cwd, 'apps/web/src') });
  const files = planGeneratePages(models);
  console.log(`${success('Generated')} ${files.length} files:`);
  for (const rel of files) {
    console.log(`  ${info('✓')} ${rel}`);
  }
}
