/**
 * `ship generate` — reads the project's `ship.config.ts` and emits typed SDK
 * wiring plus per-model admin pages into `apps/web/src/`. The pure render
 * helpers below are unit-testable without a real project: they take a list of
 * `ModelDefinition`s and return file contents, while the `generateAdminPages`
 * factory only adds the filesystem writes.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { lowerFirst, type FieldMap, type ModelDefinition } from '@ship/core';

/* ─────────────────────────── Label helpers ─────────────────────────── */

/**
 * Convert a camelCase field name into a human-readable label:
 * `publishedAt` → `Published At`, `title` → `Title`.
 */
export function humanize(field: string): string {
  return field
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(' ')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/* ─────────────────────────── Path planning ─────────────────────────── */

/** Relative (to `outDir`) paths that `generateAdminPages` will write. */
export function planGeneratePages(models: ModelDefinition[]): string[] {
  const paths = ['lib/admin-nav.ts', 'lib/ship.ts'];
  for (const model of models) {
    const base = `app/admin/${model.collection}`;
    paths.push(
      `${base}/page.tsx`,
      `${base}/new/page.tsx`,
      `${base}/[id]/page.tsx`,
    );
  }
  return paths;
}

/* ─────────────────────────── Renderers ─────────────────────────── */

/** `lib/admin-nav.ts` — Dashboard plus one entry per model. */
function renderNav(models: ModelDefinition[]): string {
  const items = models
    .map((m) => `  { label: '${m.name}', href: '/admin/${m.collection}' },`)
    .join('\n');
  return `// Generated by \`ship generate\` — edit freely; regenerated on next generate.
export const adminNav = [
  { label: 'Dashboard', href: '/admin' },
${items}
];
`;
}

/** `lib/ship.ts` — model re-exports and one `createModelApi` per model. */
function renderShip(models: ModelDefinition[]): string {
  const names = models.map((m) => m.name).join(', ');
  const entries = models
    .map((m) => `  ${lowerFirst(m.name)}: createModelApi(${m.name}, { url }),`)
    .join('\n');
  return `// Generated by \`ship generate\` — edit freely; regenerated on next generate.
import { ${names} } from '../../../../ship.config';
import { createModelApi } from '@ship/sdk';

export { ${names} };

const url = \`\${process.env.NEXT_PUBLIC_API_URL}/graphql\`;

export const ship = {
${entries}
};
`;
}

/** Table column definitions for a list page, ending in an Actions column. */
function renderColumns(model: ModelDefinition): string {
  const columns = Object.keys(model.fields).map(
    (field) => `    { field: '${field}', label: '${humanize(field)}' },`,
  );
  columns.push(`    {
      label: 'Actions',
      render: (row: any) => (
        <Link href={\`/admin/\${row.id}\`}>
          <ShipButton variant="ghost">Edit</ShipButton>
        </Link>
      ),
    },`);
  return columns.join('\n');
}

/** Per-field `<ShipField>` blocks shared by the create and edit pages. */
function renderFields(model: ModelDefinition): string {
  return Object.keys(model.fields)
    .map((field) => {
      const label = humanize(field);
      return [
        `        <div key="${field}">`,
        `          <label>${label}</label>`,
        `          <ShipField`,
        `            name="${field}"`,
        `            def={${model.name}.fields['${field}']}`,
        `            value={values['${field}']}`,
        `            onChange={(v) => setValues((p) => ({ ...p, ${field}: v }))}`,
        `          />`,
        `        </div>`,
      ].join('\n');
    })
    .join('\n');
}

/** `app/admin/<collection>/page.tsx` — searchable list page. */
function renderList(model: ModelDefinition): string {
  const { name, collection } = model;
  const camel = lowerFirst(name);
  return `'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ShipTable, ShipButton, ShipSearchInput } from '@ship/ui';
import { ship, ${name} } from '@/lib/ship';

const api = ship.${camel};

/**
 * ${name} list — generated by \`ship generate\`.
 */
export default function ${name}ListPage() {
  const router = useRouter();
  const [rows, setRows] = useState<any[]>([]);
  const [q, setQ] = useState('');

  useEffect(() => {
    let active = true;
    api.findMany({ q: q || undefined, take: 200 })
      .then((next) => {
        if (active) setRows(next);
      })
      .catch(() => {
        if (active) setRows([]);
      });
    return () => {
      active = false;
    };
  }, [q]);

  const columns = [
${renderColumns(model)}
  ];

  return (
    <div className="p-6">
      <div className="flex items-center justify-between">
        <h1>${name}</h1>
        <ShipButton onClick={() => router.push('/admin/${collection}/new')}>New ${name}</ShipButton>
      </div>
      <ShipSearchInput value={q} onChange={setQ} placeholder="Search" />
      <ShipTable data={rows} columns={columns} rowKey={(r) => r.id} />
    </div>
  );
}
`;
}

/** `app/admin/<collection>/new/page.tsx` — create page. */
function renderCreate(model: ModelDefinition): string {
  const { name, collection } = model;
  const camel = lowerFirst(name);
  return `'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ShipField, ShipButton } from '@ship/ui';
import { ship, ${name} } from '@/lib/ship';

const api = ship.${camel};

/**
 * New ${name} — generated by \`ship generate\`.
 */
export default function New${name}Page() {
  const router = useRouter();
  const [values, setValues] = useState<Record<string, unknown>>({});
  const [saving, setSaving] = useState(false);

  async function submit(e: { preventDefault(): void }) {
    e.preventDefault();
    setSaving(true);
    try {
      await api.create(values as any);
      router.push('/admin/${collection}');
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="p-6">
      <h1>New ${name}</h1>
      <form onSubmit={submit}>
${renderFields(model)}
        <ShipButton type="submit" disabled={saving}>{saving ? 'Saving...' : 'Save'}</ShipButton>
      </form>
    </div>
  );
}
`;
}

/** `app/admin/<collection>/[id]/page.tsx` — edit page. */
function renderEdit(model: ModelDefinition): string {
  const { name, collection } = model;
  const camel = lowerFirst(name);
  return `'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { ShipField, ShipButton } from '@ship/ui';
import { ship, ${name} } from '@/lib/ship';

const api = ship.${camel};

/**
 * Edit ${name} — generated by \`ship generate\`.
 */
export default function Edit${name}Page() {
  const router = useRouter();
  const params = useParams();
  const id = params.id as string;
  const [values, setValues] = useState<Record<string, unknown>>({});
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    let active = true;
    api.findById(id)
      .then((row) => {
        if (active && row) setValues(row as any);
      })
      .catch(() => {});
    return () => {
      active = false;
    };
  }, [id]);

  async function submit(e: { preventDefault(): void }) {
    e.preventDefault();
    setSaving(true);
    try {
      await api.update(id, values as any);
      router.push('/admin/${collection}');
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="p-6">
      <h1>Edit ${name}</h1>
      <form onSubmit={submit}>
${renderFields(model)}
        <ShipButton type="submit" disabled={saving}>{saving ? 'Saving...' : 'Save'}</ShipButton>
      </form>
    </div>
  );
}
`;
}

/* ─────────────────────────── Writers ─────────────────────────── */

async function emit(outDir: string, rel: string, content: string): Promise<void> {
  const target = join(outDir, rel);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, content, 'utf8');
}

/**
 * Write the full admin tree (nav, SDK entry, and list/create/edit pages) for
 * every model under `options.outDir`.
 */
export async function generateAdminPages(
  models: ModelDefinition[],
  options: { outDir: string },
): Promise<void> {
  const { outDir } = options;
  await emit(outDir, 'lib/admin-nav.ts', renderNav(models));
  await emit(outDir, 'lib/ship.ts', renderShip(models));
  for (const model of models) {
    const base = `app/admin/${model.collection}`;
    await emit(outDir, `${base}/page.tsx`, renderList(model));
    await emit(outDir, `${base}/new/page.tsx`, renderCreate(model));
    await emit(outDir, `${base}/[id]/page.tsx`, renderEdit(model));
  }
}

/* ─────────────────────────── CLI entry ─────────────────────────── */

/** Dynamically load `<cwd>/ship.config.ts` and return its `models`. */
export async function loadModels(cwd: string): Promise<ModelDefinition[]> {
  const configUrl = pathToFileURL(join(cwd, 'ship.config.ts')).href;
  // Dynamic import: the project config path is only known at runtime (`cwd`).
  const mod = (await import(configUrl)) as {
    default?: { models?: ModelDefinition[] };
  };
  return mod.default?.models ?? [];
}

/**
 * Run `ship generate` inside a generated project: load its config and emit the
 * admin tree under `apps/web/src`, logging each written file's relative path.
 */
export async function runGenerate(cwd: string = process.cwd()): Promise<void> {
  const models = await loadModels(cwd);
  await generateAdminPages(models, { outDir: join(cwd, 'apps/web/src') });
  console.log('Generated:');
  for (const rel of planGeneratePages(models)) {
    console.log(`  ${rel}`);
  }
}
